language: python

python:
    - 3.7

cache: pip

# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
    - pip install coveralls
    - pip install python-dateutil
    - pip install mecab-python3

script:
    - coverage run --parallel-mode --rcfile=.coveragerc setup.py test
    - coverage run --parallel-mode --rcfile=.coveragerc src/main.py --forcemecab

after_success:
    - coverage combine
    - coveralls
